apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  CHATBOT_API_KEY: {{ .Values.secrets.chatbotApiKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
