apiVersion: v1
kind: Service
metadata:
  name: policy-chatbot-svc
  namespace: policy-chatbot
spec:
  type: LoadBalancer
  selector:
    app: policy-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
