namespace: policy-chatbot

image:
  repository: us-central1-docker.pkg.dev/mongodb-gke-project/policy-chatbot/chatbot-api
  tag: latest
  pullPolicy: Always

replicas: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

secrets:
  chatbotApiKey: "demo-key-12345"
  geminiApiKey: "AIzaSyBg5bOu3COhHeYA3hBNc0_0MI8QMd-aeNU"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
